# Your Solution
version: '3.8'

services:
  book_catalog:
    image: project5.azurecr.io/book_catalog:latest
    container_name: book_catalog
    ports:
      - "8001:8000"
    environment:
      - DATABASE_URL=postgresql://sit722part5d_user:idSW2qLrAhTnjWEy5TEYx9jzgUN314qz@dpg-crrc88d6l47c73chaggg-a.oregon-postgres.render.com/sit722part5d

  inventory_management:
    image: project5.azurecr.io/inventory_management:latest
    container_name: inventory_management
    ports:
      - "8002:8000"
    environment:
      - DATABASE_URL=postgresql://sit722part5d_user:idSW2qLrAhTnjWEy5TEYx9jzgUN314qz@dpg-crrc88d6l47c73chaggg-a.oregon-postgres.render.com/sit722part5d

  